"""add roles invite sessions constraints

Revision ID: 4cc4e3c3acc0
Revises: 
Create Date: 2026-04-17 21:19:09.605837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc4e3c3acc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.create_index('ix_group_member_group_role', ['group_id', 'role'], unique=False)

    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_token', sa.String(length=64), nullable=False))
        batch_op.create_index('ix_study_group_subject', ['subject'], unique=False)
        batch_op.create_unique_constraint(None, ['invite_token'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')

    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_study_group_subject')
        batch_op.drop_column('invite_token')

    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.drop_index('ix_group_member_group_role')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
